name: 'AWS Lambda Monorepo Deploy'
description: 'Deploy AWS Lambda functions in a mono repo'
author: 'Baptiste Lombard'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  lambda-functions:
    description: 'Functions to deploy'
    required: true
  zip-params:
    description: 'Files to zip for uploading to AWS'
    required: true
  alias-name:
    description: 'Pointer to a specific Lambda function version'
    default: ''
    required: false
  layer-name:
    description: 'Additional code and content'
    default: ''
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
