name: Continuous Deployment

on: [push]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        npm ci
        npm t
